[package]
name = "bvm"
version = "0.1.0"
edition = "2021"

[dependencies]
bit-vec = "0.8.0"
hex = "0.4.3"
lazy_static = "1.5.0"
musig2 = "0.0.11"
sha2 = { version = "0.10.8", default-features = false }
