[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
bdk = { version = "0.29.0", features = ["rpc", "compiler", "keys-bip39"] }
tokio = { version = "1.39.1", features = ["full"] }
anyhow = "1.0.86"



[dev-dependencies]
testcontainers = "0.14.0"
